PROMPTS = [
    "Bowser",
    "a red object",
    "a shoe",
    "a chair",
    "a car",
    "a book",
    "a pair of glasses",
    "a coffee cup",
    "a laptop",
    "a tree",
    "a set of keys",
    "an outlet",
    "a toilet",
    "a hand",
    "a person",
    "a phone",
    "a jacket",
    "a wallet",
    "a keyboard",
]