PROMPTS = [
    ("a red car", "not a red car"),
    ("a fluffy cat", "not a fluffy cat"),
    ("a snowy mountain", "not a snowy mountain"),
    ("Bowser", "not Bowser"),
    ("a red object", "not a red object"),
    ("a dog", "not a dog"),
    ("a fire hydrant", "not a fire hydrant"),
    ("a street sign", "not a street sign"),
    ("a shoe", "not a shoe"),
    ("a chair", "not a chair"),
    ("a car", "not a car"),
    ("a bicycle", "not a bicycle"),
    ("a book", "not a book"),
    ("a pair of glasses", "not a pair of glasses"),
    ("a coffee cup", "not a coffee cup"),
    ("a metal can", "not a metal can"),
    ("a laptop", "not a laptop"),
    ("a tree", "not a tree"),
    ("a set of keys", "not a set of keys"),
    ("an outlet", "not an outlet"),
    ("a toilet", "not a toilet"),
    ("a hand", "not a hand"),
    ("a person", "not a person"),
]